### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'default')

### ISSUE THREAD

**Issue by AHOdonel** [leifermendez/bot-whatsapp#116]
Hola, estoy aprendiendo a programar y vi este proyecto y me gusto mucho, muchas gracias, estaba realizando unas pruebas y todo iva bien pero de repente aparece este error y ya no lo puedo ocupar:

C:\Users\ahernandez\Desktop\BOTWhatapp\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'default')
    at __puppeteer_evaluation_script__:14:123
    at ExecutionContext._evaluateInternal (C:\Users\ahernandez\Desktop\BOTWhatapp\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (C:\Users\ahernandez\Desktop\BOTWhatapp\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)
    at async Client.initialize (C:\Users\ahernandez\Desktop\BOTWhatapp\node_modules\whatsapp-web.js\src\Client.js:267:9)

ya intente actualizando whatsapp-web.js y @google-cloud/dialogflow y no me funciona, cualquier ayuda se agredeceria mucho.

![Captura](https://user-images.githubusercontent.com/118015577/201412026-15827164-a5ea-4756-a2e2-ea253eca405a.PNG)

**Comment by Condence** [comment]
de momento usen

npm i github:pedroslopez/whatsapp-web.js#fix-buttons-list

**Comment by victorocs** [comment]
Hi
check this solution, works for me
https://github.com/pedroslopez/whatsapp-web.js/issues/1786#issuecomment-1310333240

**Comment by AHOdonel** [comment]
Hi, thank you, It work porfectly
