### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'isMDBackend')

### ISSUE THREAD

**Issue by KyotoTxZ** [leifermendez/bot-whatsapp#117]
Hola, hoy decidi probar este proyecto (el cual esta muy bueno) pero al escanear el QR me sale este error, no se a que se deba:

C:\Users\juand\Documents\CHAT-BOTS\bot-whatsapp-main\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'isMDBackend')
    at __puppeteer_evaluation_script__:13:68
    at ExecutionContext._evaluateInternal (C:\Users\juand\Documents\CHAT-BOTS\bot-whatsapp-main\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (C:\Users\juand\Documents\CHAT-BOTS\bot-whatsapp-main\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)
    at async Client.initialize (C:\Users\juand\Documents\CHAT-BOTS\bot-whatsapp-main\node_modules\whatsapp-web.js\src\Client.js:267:9)

![Error bot-chat](https://user-images.githubusercontent.com/111383322/201992339-7d587a0e-f0cf-4236-924d-fc0ceb1f0f59.png)

Si alguien sabe como solucionarlo seria de gran ayuda, un saludo 👍

**Comment by brmeza** [comment]
npm i nanoid@3.3.4
npm i whatsapp-web.js

prueba instalando esto y vuelve a probar

**Comment by KyotoTxZ** [comment]
Bro si me servio tu solucion, muchas gracias 💯
