### ISSUE TITLE
Error al leer QR con WA Bussines 

### ISSUE THREAD

**Issue by sulivan22** [leifermendez/bot-whatsapp#16]
Hola,

     Si escaneo el código con WA bussines el teléfono lo vincula bien pero sale el siguiente error en la terminal y no se crea el archivo de session.jon.

     WA normal si funciona.

Ver QR http://localhost:3004/qr
(node:4775) UnhandledPromiseRejectionWarning: Error: Authenticating via JSON session is not supported for MultiDevice-enabled WhatsApp accounts.
    at LegacySessionAuth.getAuthEventPayload (/Users/sulivan/Desktop/ChatBot/node_modules/whatsapp-web.js/src/authStrategies/LegacySessionAuth.js:57:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Client.initialize (/Users/sulivan/Desktop/ChatBot/node_modules/whatsapp-web.js/src/Client.js:217:34)
(node:4775) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4775) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

<img width="1347" alt="Captura de pantalla 2022-03-08 a las 13 12 57" src="https://user-images.githubusercontent.com/4517942/157236149-24ba0020-febb-459c-93f3-d3447ee0865f.png">

**Comment by leifermendez** [comment]
https://github.com/leifermendez/bot-whatsapp#atencion-1-  ese error lo explico aquí

**Comment by DaironAmador** [comment]
Más o menos a una solución temporal a ese problemilla hasta que @leifermendez pueda resolverlo en su totalidad, simplemente comenta el código que comprueba si es Multi-Device.

Ojo: tendrás que escanear el QR cada vez que inicies sesión y no te funcionaran algunas cosas como los botones :c

**Comment by sulivan22** [comment]
ok, lo mirare, es que esa otra linea no esta en el beta-tester
Gracias!
