### ISSUE TITLE
Intentando tu ejemplo de dialogflow

### ISSUE THREAD

**Issue by hunimato** [leifermendez/bot-whatsapp#32]
Hola, 

Intentando tu ejemplo de Dialog Flow, cuando escribo hola, no recibo la respuesta de dialgo flow

Recibo en consola el siguiente texto

"Listo para escuchas mensajes
Client is ready!
BODY hola"

En mi whatsapp no recibo respuesta.

Gracias,

Hugo

**Comment by DavidVega707** [comment]
Tengo el mismo problema preferiría un error a esto.

**Comment by hunimato** [comment]
Me pasa igual, si logro avanzar en algo te lo comento, mi mail es hunimato@gmail.com.

Te pido que si lo solucionas me ayudes.

Gracias

Saludos

**Comment by izelaya051290** [comment]
Un saludo Leifer!, Muchas gracias por tus aportes, nos enseñas cada vez mas a los que venismos empezando en programacion, yo tengo el Mismo problema con dialogflow

**Comment by DavidVega707** [comment]
La única solución momentánea que encontré es usando una versión anterior del bot en concreto esta[https://github.com/leifermendez/bot-whatsapp/tree/5aaf761fce0f4ad1df00ed425259114f37b1f8a4](url)

**Comment by leifermendez** [comment]
Perfecto lo reviso para implementar

**Comment by hunimato** [comment]
Hola resolvi el problema.

Comenten la linea 57 de app.js.

Saludos,

Hugo

![image](https://user-images.githubusercontent.com/58860926/159086325-ef09ae06-a2bf-4189-97a9-874f3521e7d3.png)

**Comment by izelaya051290** [comment]
REsuelto, Gracias @hunimato @leifermendez

**Comment by hunimato** [comment]
@izelaya051290 si quieres escribime a mi mail asi compartimos conocimientos. Soy nuevo en esto !

**Comment by hunimato** [comment]
> @izelaya051290 si quieres escribime a mi mail asi compartimos conocimientos. Soy nuevo en esto !

hunimato@gmail.com

**Comment by hunimato** [comment]
> Tengo el mismo problema preferiría un error a esto.

Quedo solucionado @DavidVega707 @tonyvazgar

**Comment by sucoabedrabbo** [comment]
Hola amigos como están la verdad soy bastante nuevo en esto de js, he estado probando y no logro conectarlo a dialogflow  tengo este error 

2022-03-28T14:14:28.989912+00:00 app[web.1]: BODY h
2022-03-28T14:14:29.048903+00:00 app[web.1]: (node:22) UnhandledPromiseRejectionWarning: Error: 3 INVALID_ARGUMENT: com.google.apps.framework.request.BadRequestException: query_input.text.language_code is not set.
2022-03-28T14:14:29.048905+00:00 app[web.1]:     at Object.callErrorFromStatus (/app/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
2022-03-28T14:14:29.048906+00:00 app[web.1]:     at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client.js:180:52)
2022-03-28T14:14:29.048907+00:00 app[web.1]:     at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)
2022-03-28T14:14:29.048907+00:00 app[web.1]:     at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
2022-03-28T14:14:29.048908+00:00 app[web.1]:     at /app/node_modules/@grpc/grpc-js/build/src/call-stream.js:182:78
2022-03-28T14:14:29.048908+00:00 app[web.1]:     at processTicksAndRejections (internal/process/task_queues.js:77:11)
2022-03-28T14:14:29.049780+00:00 app[web.1]: (node:22) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)

algún comentario...??? quedo agradecido a cualquier ayuda.

Salim

**Comment by sucoabedrabbo** [comment]
Hola nuevamente lo logre resolver muchas gracias

**Comment by leifermendez** [comment]
@sucoabedrabbo Si gustas podrias compartir tu solucion :)

**Comment by sucoabedrabbo** [comment]
claro @leifermendez  con gusto corríjanme si estoy equivocado ya que soy nuevo en js,
en la linea 41 de dialogflow.js

languageCode: languageCode
este comando ve el lenguaje del sistema en mi caso lo tengo en ingles, pero todo el proceso esta en español 
lo comente y lo pase directamente a : 
languageCode: "es-ES"

quedo atento a sus comentarios

**Comment by leifermendez** [comment]
Buenas este bug ya esta corregido esperar en el día subo update
