### ISSUE TITLE
Dockerizar la app // Cloud

### ISSUE THREAD

**Issue by sulivan22** [leifermendez/bot-whatsapp#42]
Buenos Días!

    Para usar el bot en la cloud he intentado usarlo como app en node o docker y siempre da error de puppeter/Chromium,   bien sean en NODE o Docker

    Me da el siguiente error.

$ docker run chatbot/chatbot:v9

> chatbot@1.0.0 start /app
> node ./app.js

El server esta listo por el puerto 3000
(node:21) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
[0331/105305.297443:FATAL:zygote_host_impl_linux.cc(117)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/main/docs/linux/suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
#0 0x562ab8347469 base::debug::CollectStackTrace()
#1 0x562ab82adf33 base::debug::StackTrace::StackTrace()
#2 0x562ab82c0d50 logging::LogMessage::~LogMessage()
#3 0x562ab63815db content::ZygoteHostImpl::Init()
#4 0x562ab7e5adf2 content::ContentMainRunnerImpl::Initialize()
#5 0x562ab7e58eb9 content::RunContentProcess()
#6 0x562ab7e5900e content::ContentMain()
#7 0x562ab7eb3fca headless::(anonymous namespace)::RunContentMain()
#8 0x562ab7eb3cd5 headless::HeadlessShellMain()
#9 0x562ab4aa5668 ChromeMain
#10 0x7f407f9002e1 __libc_start_main
#11 0x562ab4aa54aa _start

Received signal 6
#0 0x562ab8347469 base::debug::CollectStackTrace()
#1 0x562ab82adf33 base::debug::StackTrace::StackTrace()
#2 0x562ab8346f71 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#3 0x7f40840710e0 (/lib/x86_64-linux-gnu/libpthread-2.24.so+0x110df)
#4 0x7f407f912fff gsignal
#5 0x7f407f91442a abort
#6 0x562ab83461f5 base::debug::BreakDebuggerAsyncSafe()
#7 0x562ab82c1221 logging::LogMessage::~LogMessage()
#8 0x562ab63815db content::ZygoteHostImpl::Init()
#9 0x562ab7e5adf2 content::ContentMainRunnerImpl::Initialize()
#10 0x562ab7e58eb9 content::RunContentProcess()
#11 0x562ab7e5900e content::ContentMain()
#12 0x562ab7eb3fca headless::(anonymous namespace)::RunContentMain()
#13 0x562ab7eb3cd5 headless::HeadlessShellMain()
#14 0x562ab4aa5668 ChromeMain
#15 0x7f407f9002e1 __libc_start_main
#16 0x562ab4aa54aa _start
  r8: 0000000000000000  r9: 00007ffc4964df80 r10: 0000000000000008 r11: 0000000000000246
 r12: 00007ffc4964f240 r13: 00007ffc4964f258 r14: 00007ffc4964f250 r15: 00002ea200238800
  di: 0000000000000002  si: 00007ffc4964df80  bp: 00007ffc4964e1c0  bx: 0000000000000006
  dx: 0000000000000000  ax: 0000000000000000  cx: 00007f407f912fff  sp: 00007ffc4964dff8
  ip: 00007f407f912fff efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/app/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:237:20)
    at Interface.<anonymous> (/app/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:227:68)
    at Interface.emit (events.js:327:22)
    at Interface.close (readline.js:424:8)
    at Socket.onend (readline.js:202:10)
    at Socket.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1223:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:21) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:21) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Dockerfile 

FROM node:14.1
WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN apt-get update && \
    apt-get -y install xvfb gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 \
      libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 \
      libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 \
      libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 \
      libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget && \
    rm -rf /var/lib/apt/lists/*

# Add user so we don't need --no-sandbox.
RUN groupadd -r pptruser && useradd -r -g pptruser -G audio,video pptruser \
    && mkdir -p /home/pptruser/Downloads \
    && chown -R pptruser:pptruser /home/pptruser

# Run everything after as non-privileged user.

USER pptruser

CMD ["npm","start"]

     También lo intente usar como root pero me pide usar con user según  https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

     Alguna sugerencia para correrlo en la nube, lo intente en google cloud, DigitalOcean etc etc

Gracias

**Comment by leifermendez** [comment]
@sulivan22 lo solcuionaste?

**Comment by sulivan22** [comment]
solucionado lo del docker pero ahora me salta lo del multidevice :( 


Ver QR http://localhost:3000/qr
⚡ Recuerda que el QR se actualiza cada minuto ⚡'
⚡ Actualiza F5 el navegador para mantener el mejor QR⚡
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ █▀▄█▄  ▄█  ▀▀ ██ ▄█  ▀▄▄▀ █▄▄█▀ ▄▄  ▀██ ▄▄▄▄▄ █
█ █   █ █▄ ▄▀▄█▄▀▄▀█  ▄█▀ ▄█ ▄▀▄████▀█▄███ ▀▄▀█ █   █ █
█ █▄▄▄█ █ ▄▀ ▄▄█ ▀▄▀█  ██ ▄▄▄ ▄▄   ▀██▄▄    ███ █▄▄▄█ █
█▄▄▄▄▄▄▄█ ▀▄█ █ ▀ █▄█ ▀▄▀ █▄█ ▀ █▄▀ █ █ ▀▄█▄▀ █▄▄▄▄▄▄▄█
█  ▀ ▀▀▄ █▄▀█  ▄█ ▀▄█▄ ▄▄  ▄▄ ▄▄▄███  ██ ▄ █ ▄█▄▄ ▀ ▄▀█
██▄█▀▄█▄█▀▄▀▄▀█▀█ ▄ ▀▄▄█▀▄█▀▀█▀▀▄██████▀▀▀▄█▀▄ ▀▄ ▀  ▀█
████▄▄ ▄▀▀▄▄ ▄▄ ▄▀█ ▀▄ ▄███ ▄ █▄  █ ▄  █▄ ██▀▄█▀ ▄█▀ ▄█
██ ▄█ ▄▄█▄▄ █▄██▄███▀██  ██▄  █  ▀▀▀█▄ ▄▄ █▄▀▄▄▄██▄█▄▄█
█▀ ▀ ██▄▀▀▄▀▄▄▄  █▄ █▀▄▀  ▄██▄ ▄▀ ▄█▄ ▄▀ █▀██ ▄█▄▄▀█▄ █
█▄ ▄█▀ ▄██████▀█  ▀ ▄ ▀▀ █▀▄▄▄▄██▀ ▄ ▄▄█ ▄▄█▀▄▀  █ █▄ █
█ ▄▄█▀ ▄▀▀▀ █ ▄█ █▀ ▄█ ▄▀█▀▀ ▄▄▄▄███▀ █▄▄  ▄▄██▄▀▄██▀ █
█▄▄▄▀ ▀▄ ▀▀▄█▀▀█ ▀▄█ ▀ █▄██ ▄█▄▄▄▄▄██ ▀█▀▀█▀ ▀█▄▄█▄▀ ▀█
█ ▄█▀ ▄▄▄ ▀█▄▄▄██▄█ ▀█    ▄▄▄ ▄▄▀▄█▀ ▄▀█▄▄▄▄  ▄▄▄ ▀████
█▄▀▀▄ █▄█  ▀█  ▀█▀▀█▀█▀██ █▄█ ▀█▄▀▀▀ █ ▀▄ █ ▀ █▄█ ██▀▄█
█ ▀ █▄▄▄▄▄▄█  ▀ ▄▄  █▀▀▀█ ▄ ▄ ▀█▀▄▀▄ ▄█  █ █ ▄ ▄ ▄▄████
█  ▀█▄ ▄▄█ █▀▀▀▄██▀▄█ ▄▄▀██▀█▀▄▄ █▀█ ▄▀▄▄▄▄██▀ ▄▄█ ▄▄ █
██  ▀█ ▄▄ ▄▄ ███ ▄▄  ▄  ▄█▄█▄██▄▄▀▄▄█▄█▄  ███▄ ▄ █ ▄▀▄█
█  █▀ █▄▄▀▀██▄▄█ ███ █▄ ██  ████▀▄▀ ▀▀ ▀▄▀ ▄▄▄▄▀  ▄▀ ▀█
█▄  █  ▄▄█▀ █ ▄ █▀█ ▀█  ▀▀▄▄ ▄██▄▄▄▀ ▄ █ ▄▄█▀ ▄██▄▄▄█▄█
█▀ █ ▀▀▄▄█▀█▀▀    ██    ▄█ ▀▄▄ ▄▄▄█▄▄▄ ▄▀ █▄▄ █ ▀▄ ▄▄▄█
██ ▀▀▄▀▄▄▀  █▀▀▀█▀█▄█▀▄██▀▀▄▄▄▀█▀▄▄█▄▄█▀ ▀ ▄▄  █▄██▀█ █
█▄ ▀▄▄▄▄▀▀▄█▀ ▄███▄ ▀▄█▄▀█▄▀▄▀▀█▄▀▄ ▄▀▀▄ ▄█▄█ ▄▄ ▀ ██ █
████▄██▄▄▀▄▀█▄▄ ██▀▄█▄  ▄ ▄▄▄  ███▀█▄ ██▄ ██▀ ▄▄▄ ▀████
█ ▄▄▄▄▄ █▄█▄  ▀█ █▄▀▄▄▀   █▄█  ▀▀▀  ▄█ ▄    █ █▄█ ▄▀▄▀█
█ █   █ █▀▀▄█ ▀▀   █▄█  █▄ ▄▄  ▄  █▀▄▄ ▄ ▄█▄▄    ▄███ █
█ █▄▄▄█ █▀▄  █▄▄ ▄█▄▄   █ █  ▄██▄▀▀█ ▀▄█▀ ▄█ ▀▄██ ▄▄ ██
█▄▄▄▄▄▄▄█▄█▄███▄▄▄▄▄▄█▄█▄▄▄█▄█▄█▄▄███▄█▄▄██▄▄██▄▄▄▄█▄██

Ver QR http://localhost:3000/qr
(node:20) UnhandledPromiseRejectionWarning: Error: Authenticating via JSON session is not supported for MultiDevice-enabled WhatsApp accounts.
    at LegacySessionAuth.getAuthEventPayload (/app/node_modules/whatsapp-web.js/src/authStrategies/LegacySessionAuth.js:57:24)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Client.initialize (/app/node_modules/whatsapp-web.js/src/Client.js:217:34)

**Comment by leifermendez** [comment]
@sulivan22 en tu .env MULTI_DEVICE=true

**Comment by sulivan22** [comment]
@leifermendez  si, pero como que no toma efecto 

DEFAULT_MESSAGE=false
SAVE_MEDIA=false
PORT=3000
DATABASE=none
LANGUAGE=es
SQL_HOST=
SQL_USER=
SQL_PASS=
SQL_DATABASE=
MULTI_DEVICE=true

     al lanzar el docker se baja el paquete de nuevo y por ende  la linea de multidevice de descomenta. Por eso me salta el error

/src/authStrategies/LegacySessionAuth.js:57:24
if (isMD) throw new Error('Authenticating via JSON session is not supported for MultiDevice-enabled WhatsApp accounts.');

**Comment by sulivan22** [comment]
he descargado el código de nuevo y ya me funciona en Docker correctamente!
Gracias
