### ISSUE TITLE
Cuando recibo un mensaje de Grupos de WhatsApp se rompe la conexión y se detienen los procesos. Alguien sabe como resolver este issue? Grupos de WhatsApp: Los Mensajes que envian en los Grupos tumba la conexion. Sabe alguien Ignorar los "msj de grupos" o solucionar este Issue?

### ISSUE THREAD

**Issue by alonzomiguel** [leifermendez/bot-whatsapp#45]
Error: Evaluation failed: Error: wid error: invalid wid: 18299948875-1620841531@g.us@c.us
    at new c (https://web.whatsapp.com/bootstrap_qr.8e365468263647825bd5.js:69:26446)
    at Object.s [as createWid] (https://web.whatsapp.com/bootstrap_qr.8e365468263647825bd5.js:69:30732)
    at __puppeteer_evaluation_script__:2:53
    at ExecutionContext._evaluateInternal (C:\dev\bot-whatapp-dbjson\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (C:\dev\bot-whatapp-dbjson\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)
    at async Client.sendMessage (C:\dev\bot-whatapp-dbjson\node_modules\whatsapp-web.js\src\Client.js:594:28)

**Comment by alonzomiguel** [comment]
Bug Mejor Explicado: cuando recibo un mensaje de un Grupo de WhatsApp se rompe la conexión y detiene el proceso y debo volver a ejecutar "npm start". Alguien sabe como resolver este issue?

**Comment by leifermendez** [comment]
Solucioando en el transcurso del día subo update

**Comment by alonzomiguel** [comment]
Wao!! Leifer muchas gracias!!te mereces un bue cafe!! voy estar pendiente para probarlo cuando lo subas.
